config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :blogs do
    resources :comments
  end

  resources :product_reviews

  resources :articles

  get 'email_article/:id',
      to: 'articles#article_email',
      as: 'email_article'

  resources :puzzles

  devise_for :users

  # Edit User
  devise_scope :user do
    get 'preferences',
        to: 'devise/registrations#edit',
        as: 'preferences'
  end

  resources :reviews

  resources :products do
    resources :product_reviews
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
    resources :reviews
  end

  get 'email_restaurant/:id',
      to: 'restaurants#email_restaurant',
      as: 'email_restaurant'

  post '/puzzles/new',
       to: 'puzzles#create'

  get 'maps',
      to: 'page#maps',
      as: 'maps'

  # get 'page/articles'
  get 'articles',
      to: 'page#articles',
      as: 'articles_url'

  get 'restaurants',
      to: 'page#restaurants',
      as: 'restaurants_url'

  get 'products',
      to: 'page#products',
      as: 'products_url'

  get 'store',
      to: 'store#index',
      as: 'store'

  get 'store/:id',
      to: 'store#show',
      as: 'store_show'


  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'login',
      to: 'page#login',
      as: 'login'

  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord

  validates_presence_of :title, :author,
                        :published_date,
                        :content, :avatar_thumbnail

  paginates_per 10

  after_save do |article|
    if article.published
      User.where(newsletter: true).each do |user|
        UserMailer.article_email(user, article).deliver_now
      end
    end
  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :set_article, only: [:show, :edit, :update, :destroy, :article_email]
  before_action :authenticate_admin, only: [:edit, :update, :destroy, :create, :new]


  def article_email
    # Send email to all users that want newsletters
    @users = User.where(newsletter: true)
    @users.each do | user |
      UserMailer.article_email(user, @article).deliver_now
    end
    redirect_to articles_path, notice: 'Article emailed!'
  end

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all.order('created_at DESC').page(params[:page])
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :author, :published_date, :published, :content, :avatar_thumbnail)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :article_title, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :author %>
    <%= form.text_field :author, id: :article_author, class: 'fullwidth' %>
  </div>

  <div class="field date-select">
    <%= form.label :published_date %>
    <%= form.datetime_select :published_date, {:prompt => true}, id: :article_published_date %>
  </div>

  <div class="field">
    <%= form.label :published %>
    <%= form.check_box :published, id: :article_published, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :article_content, class: 'fullwidth tinymce' %>
  </div>

  <div class="field">
    <%= form.label :avatar_thumbnail %>
    <%= form.text_field :avatar_thumbnail, id: :article_avatar_thumbnail, class: 'fullwidth' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<% provide(:title, "Edit #{@article.title}") %>
<% provide(:page, 'Articles')  %>

<section class="edit">

  <div class="section-header">
    <h2>Editing: <%= @article.title %></h2>
  </div>

  <div class="form-wrapper">

    <%= render 'form', article: @article %>

    <%= link_to 'Show', @article, class: 'button' %>
    <%= link_to 'Back', articles_path, class: 'button' %>

  </div>

</section>

app/views/articles/index.html.erb
<% provide(:title, 'Articles') %>
<% provide(:page, 'Articles')  %>

<section class="articles">

  <div class="section-header">
    <h2>Articles</h2>
  </div>

  <% if current_user.try(:admin?) %>
    <%= link_to 'New Article', new_article_path, class: 'button' %>
  <% end %>
  <div class="table-wrapper">

    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Author</th>
          <th>Published date</th>
          <th>Published</th>
          <th>Content</th>
          <th>Avatar thumbnail</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @articles.each do |article| %>
          <tr>
            <td><%= article.title %></td>
            <td><%= article.author %></td>
            <td><%= article.published_date %></td>
            <td><%= article.published %></td>
            <td><%= article.content.html_safe %></td>
            <td><%= article.avatar_thumbnail.truncate(20) %></td>
            <td><%= link_to 'Show', article %></td>
            <% if current_user.try(:admin?) %>
              <td><%= link_to 'Edit', edit_article_path(article) %></td>
              <td><%= link_to 'Destroy', article, method: :delete, data: {confirm: 'Are you sure?'} %></td>
              <td><%= link_to 'Email', email_article_path(article) %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>

  <%= paginate @articles %>


</section>

app/views/articles/new.html.erb
<% provide(:title, 'New Article') %>
<% provide(:page, 'Articles')  %>

<section class="new">

  <div class="section-header">
    <h2>Write an article</h2>
  </div>

  <div class="form-wrapper">

    <%= render 'form', article: @article %>
    <%= link_to 'Back', articles_path, class: 'button' %>

  </div>

</section>

app/views/articles/show.html.erb
<% provide(:title, @article.title) %>
<% provide(:page, 'Articles')  %>

<section class="product">

  <div class="section-header">
    <h2><%= @article.title %></h2>
  </div>

  <div class="details-container">

    <p>
      <strong>Author:</strong>
      <%= @article.author %>
    </p>

    <p>
      <strong>Published date:</strong>
      <%= @article.published_date %>
    </p>

    <p>
      <strong>Published:</strong>
      <%= @article.published %>
    </p>

    <p>
      <strong>Content:</strong>
      <%= @article.content.html_safe %>
    </p>

    <p>
      <strong>Avatar thumbnail:</strong>
      <br>
      <%= image_tag @article.avatar_thumbnail %>
    </p>

    <% if current_user.try(:admin?) %>
      <%= link_to 'Edit', edit_article_path(@article), class: 'button' %>
    <% end %>
    <%= link_to 'Back', articles_path, class: 'button' %>

  </div>

</section>