config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :blogs do
    resources :comments
  end

  resources :product_reviews

  resources :articles

  get 'email_article/:id',
      to: 'articles#article_email',
      as: 'email_article'

  resources :puzzles

  devise_for :users

  # Edit User
  devise_scope :user do
    get 'preferences',
        to: 'devise/registrations#edit',
        as: 'preferences'
  end

  resources :reviews

  resources :products do
    resources :product_reviews
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
    resources :reviews
  end

  get 'email_restaurant/:id',
      to: 'restaurants#email_restaurant',
      as: 'email_restaurant'

  post '/puzzles/new',
       to: 'puzzles#create'

  get 'maps',
      to: 'page#maps',
      as: 'maps'

  # get 'page/articles'
  get 'articles',
      to: 'page#articles',
      as: 'articles_url'

  get 'restaurants',
      to: 'page#restaurants',
      as: 'restaurants_url'

  get 'products',
      to: 'page#products',
      as: 'products_url'

  get 'store',
      to: 'store#index',
      as: 'store'

  get 'store/:id',
      to: 'store#show',
      as: 'store_show'


  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'login',
      to: 'page#login',
      as: 'login'

  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_nav.html.erb
<nav id="site-navigation" class="main-navigation" aria-labelledby="site-navigation-label"
     itemscope="" itemtype="https://schema.org/SiteNavigationElement">

  <h2 class="screen-reader-text" id="site-navigation-label">Primary Menu</h2>


  <div id="main-navigation-inner" class="main-navigation-inner">

    <div class="menu">
      <ul role="menu">
        <%- # nav_link_to is in ApplicationHelper %>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Home', root_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Restaurants', restaurants_url_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Products', store_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Blog', blogs_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Articles', articles_url_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Calendar', calendar_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Contact Us', contact_us_path %>
        </li>
        <li class="menu-item" role="menuitem">
          <%= nav_link_to 'Puzzle', new_puzzle_path %>
        </li>

        <% if user_signed_in? %>

          <li class="menu-item menu-item-has-children" role="menuitem">

            <%= link_to('Logout <span class="expander" aria-hidden="true"></span>'.html_safe, destroy_user_session_path, method: :delete) %>

            <ul class="sub-menu" role="menu">
              <li class="menu-item" role="menuitem">
                <%= nav_link_to 'Preferences', preferences_path %>
              </li>
            </ul>

          </li>

          <li>
            Welcome, <%= current_user.name %>
          </li>
        <% else %>

          <li class="menu-item" role="menuitem">
            <%= nav_link_to('Login', new_user_session_path) %>
          </li>
          <li class="menu-item" role="menuitem">
            <%= nav_link_to('Register', new_user_registration_path) %>
          </li>

        <% end %>

      </ul>
    </div>

  </div>

  <button id="menu-toggle" class="menu-toggle" aria-controls="site-navigation" aria-expanded="true">Menu</button>

</nav>