config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :blogs do
    resources :comments
  end

  resources :product_reviews

  resources :articles

  get 'email_article/:id',
      to: 'articles#article_email',
      as: 'email_article'

  resources :puzzles

  devise_for :users

  # Edit User
  devise_scope :user do
    get 'preferences',
        to: 'devise/registrations#edit',
        as: 'preferences'
  end

  resources :reviews

  resources :products do
    resources :product_reviews
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
    resources :reviews
  end

  get 'email_restaurant/:id',
      to: 'restaurants#email_restaurant',
      as: 'email_restaurant'

  post '/puzzles/new',
       to: 'puzzles#create'

  get 'maps',
      to: 'page#maps',
      as: 'maps'

  # get 'page/articles'
  get 'articles',
      to: 'page#articles',
      as: 'articles_url'

  get 'restaurants',
      to: 'page#restaurants',
      as: 'restaurants_url'

  get 'products',
      to: 'page#products',
      as: 'products_url'

  get 'store',
      to: 'store#index',
      as: 'store'

  get 'store/:id',
      to: 'store#show',
      as: 'store_show'


  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'login',
      to: 'page#login',
      as: 'login'

  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

  has_many :reviews, dependent: :destroy

  validates_presence_of :name, :location, :cuisine, :tags, :image
  validates :low_price_range, :high_price_range, numericality: {greater_than: 0}

  paginates_per 10

  after_save do |restaurant|
    User.where(newsletter: true).each do |user|
      UserMailer.restaurant_email(user, restaurant).deliver_now
    end
  end

end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  before_action :set_restaurant, only: [:show, :edit, :update, :destroy, :email_restaurant]

  before_action :authenticate_admin, only: [:edit, :update, :destroy, :create, :new]

  # Email restaurant
  def email_restaurant
    # Send email to all users that want newsletters
    @users = User.where(newsletter: true)
    @users.each do | user |
      UserMailer.restaurant_email(user, @restaurant).deliver_now
    end
    redirect_to restaurants_path, notice: 'Restaurant emailed!'
  end

  # GET /restaurants
  # GET /restaurants.json
  def index
    # @page = params[:page].to_i
    # @per_page = params[:per].to_i
    # @offset = (@page - 1) * @per_page
    @restaurants = Restaurant.page(params[:page])
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully created.' }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: 'Restaurant was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: 'Restaurant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :location, :cuisine, :image, :low_price_range, :high_price_range, :tags)
    end

end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<%= form_with(model: restaurant, local: true) do |form| %>
  <% if restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :restaurant_name, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :location %>
    <%= form.text_area :location, id: :restaurant_location, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :cuisine %>
    <%= form.text_field :cuisine, id: :restaurant_cuisine, class: 'fullwidth' %>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.text_field :image, id: :restaurant_image, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :low_price_range %>
    <%= form.text_field :low_price_range, id: :restaurant_low_price_range, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :high_price_range %>
    <%= form.text_field :high_price_range, id: :restaurant_high_price_range, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :tags %>
    <%= form.text_area :tags, id: :restaurant_tags, class: 'fullwidth' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/restaurants/_restaurants.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Location</th>
      <th>Cuisine</th>
      <th>Image</th>
      <th>Low price range</th>
      <th>High price range</th>
      <th>Tags</th>
      <th>Rating</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.id %></td>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.location %></td>
        <td><%= restaurant.cuisine %></td>
        <td><%= restaurant.image.truncate(20) %></td>
        <td><%= number_to_currency restaurant.low_price_range %></td>
        <td><%= number_to_currency restaurant.high_price_range %></td>
        <td><%= restaurant.tags.truncate(20) %></td>
        <td>
          <% if restaurant.reviews.any? %>
            <%= ((image_tag 'fork.png', size: '20x20') * restaurant.reviews.average(:rating)).html_safe %>
          <% end %>
        </td>
        <td><%= link_to 'Show', restaurant %></td>
        <% if current_user.try(:admin?) %>
          <td><%= link_to 'Edit', edit_restaurant_path(restaurant) %></td>
          <td><%= link_to 'Destroy', restaurant, method: :delete, data: {confirm: 'Are you sure?'} %></td>
          <td><%= link_to 'Email', email_restaurant_path(restaurant) %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/restaurants/edit.html.erb
<% provide(:title, "Edit #{@restaurant.name}") %>
<% provide(:page, 'Restaurants')  %>

<section class="edit">

  <div class="section-header">
    <h2>Editing: <%= @restaurant.name %></h2>
  </div>

  <div class="form-wrapper">

    <%= render 'form', restaurant: @restaurant %>

    <%= link_to 'Back', restaurants_path, class: 'button' %>
    <%= link_to 'Show', @restaurant, class: 'button' %>

  </div>


</section>

app/views/restaurants/index.html.erb
<% provide(:title, 'Restaurants') %>
<% provide(:page, 'Restaurants')  %>

<section class="restaurants">

  <div class="section-header">
    <h2>Restaurants</h2>
  </div>

  <% if current_user.try(:admin?) %>
    <%= link_to 'New Restaurant', new_restaurant_path, class: 'button' %>
  <% end %>

  <div class="table-wrapper" id="restaurants">
    <%= render 'restaurants' %>
  </div>

  <div id="paginate-restaurants">
    <%= paginate @restaurants, remote: true %>
  </div>


</section>

app/views/restaurants/index.js.erb
$(function() {
  $('#restaurants').html("<%= escape_javascript( render('restaurants') ) %>");
  $('#paginate-restaurants').html("<%= escape_javascript( paginate @restaurants, remote: true ).to_s %>");
});

app/views/restaurants/new.html.erb
<% provide(:title, 'New Restaurant') %>
<% provide(:page, 'Restaurants')  %>

<section class="new">

  <div class="section-header">
    <h2>Create a new restaurant</h2>
  </div>

  <div class="form-wrapper">
    <%= render 'form', restaurant: @restaurant %>

    <%= link_to 'Back', restaurants_path, class: 'button' %>
  </div>

</section>

app/views/restaurants/pagination.js.erb
$('#paginate-restaurants').html("<%= escape_javascript( paginate @restaurants, remote: true ).to_s %>")

app/views/restaurants/show.html.erb
<%= tinymce %>
<% provide(:title, @restaurant.name) %>
<% provide(:page, 'Restaurants')  %>

<section class="restaurant">

  <div class="section-header">
    <h2><%= @restaurant.name %></h2>
    <% if @restaurant.reviews.any? %>
      <p>
        Rated: <%= ((image_tag 'fork.png', size: '20x20') * @restaurant.reviews.average(:rating)).html_safe %>
      </p>
    <% end %>
  </div>

  <div class="details-container">

    <p>
      <strong>Location:</strong>
      <%= @restaurant.location %>
    </p>

    <p>
      <strong>Cuisine:</strong>
      <%= @restaurant.cuisine %>
    </p>
    <p>
      <strong>Image:</strong>
      <br>
      <%= image_tag @restaurant.image %>
    </p>

    <p>
      <strong>Low price range:</strong>
      <%= number_to_currency @restaurant.low_price_range %>
    </p>

    <p>
      <strong>High price range:</strong>
      <%= number_to_currency @restaurant.high_price_range %>
    </p>

    <p>
      <strong>Tags:</strong>
      <%= @restaurant.tags %>
    </p>

    <div>
      <strong>Reviews:</strong>
      <% @restaurant.reviews.each do |review| %>
        <p>
          By: <%= review.name %><br>
          Rating: <%= ((image_tag 'fork.png', size: '20x20') * review.rating).html_safe %><br>
          <%= review.review_text.html_safe %><br>
          Date: <%= time_ago_in_words review.created_at %><br>
          <% if current_user.try(:admin) %>
            <%= link_to 'Remove', restaurant_review_path(@restaurant, review), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </p>
      <% end %>
    </div>

    <% if user_signed_in? %>

      <div class="reviews">

        <%= form_for [@restaurant, @restaurant.reviews.build] do |form| %>
          <div class="field">
            <%= form.label :name %>
            <%= form.text_field :name, id: :review_name, class: 'fullwidth' %>
          </div>

          <div class="field">
            <%= form.label :review_text %>
            <%= form.text_area :review_text, id: :review_review_text, class: 'fullwidth tinymce' %>
          </div>

          <div class="field">
            <%= form.label :rating %>
            <%= form.number_field :rating, id: :review_rating, class: 'fullwidth' %>
          </div>

          <div class="field">
            <%= form.hidden_field :restaurant_id %>
          </div>

          <div class="actions">
            <%= form.submit %>
          </div>

        <% end %>

      </div>

      <%= link_to 'Back', restaurants_path, class: 'button' %>
      <% if user_signed_in? && current_user.admin %>
        <%= link_to 'Edit', edit_restaurant_path(@restaurant), class: 'button' %>
      <% end %>

      </div>

    <% end %>

    </section>