config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :blogs do
    resources :comments
  end

  resources :product_reviews

  resources :articles

  get 'email_article/:id',
      to: 'articles#article_email',
      as: 'email_article'

  resources :puzzles

  devise_for :users

  # Edit User
  devise_scope :user do
    get 'preferences',
        to: 'devise/registrations#edit',
        as: 'preferences'
  end

  resources :reviews

  resources :products do
    resources :product_reviews
  end

  resources :restaurants do
    get 'page/:page', action: :index, on: :collection
    resources :reviews
  end

  get 'email_restaurant/:id',
      to: 'restaurants#email_restaurant',
      as: 'email_restaurant'

  post '/puzzles/new',
       to: 'puzzles#create'

  get 'maps',
      to: 'page#maps',
      as: 'maps'

  # get 'page/articles'
  get 'articles',
      to: 'page#articles',
      as: 'articles_url'

  get 'restaurants',
      to: 'page#restaurants',
      as: 'restaurants_url'

  get 'products',
      to: 'page#products',
      as: 'products_url'

  get 'store',
      to: 'store#index',
      as: 'store'

  get 'store/:id',
      to: 'store#show',
      as: 'store_show'


  get 'calendar((/:month)/:year)',
      to: 'page#calendar',
      as: 'calendar'

  get 'contact_us',
      to: 'page#contact_us',
      as: 'contact_us'

  get 'login',
      to: 'page#login',
      as: 'login'

  root 'page#home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord

  has_many :product_reviews, dependent: :destroy

  validates_presence_of :name, :description,
                        :image_thumbnail, :image_full,
                        message: 'is required.'
  validates_numericality_of :quantity_on_hand, :selling_price,
                            :cost_of_product, :shipping_weight,
                            message: 'is required to be a number.'
  paginates_per 10
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_admin
  before_action :set_product, only: [:show, :edit, :update, :destroy]


  # GET /products
  # GET /products.json
  def index
    @products = Product.all.page params[:page]
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :description, :quantity_on_hand, :selling_price, :cost_of_product, :shipping_weight, :image_thumbnail, :image_full)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :product_name, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :product_description, class: 'fullwidth tinymce' %>
  </div>

  <div class="field">
    <%= form.label :quantity_on_hand %>
    <%= form.number_field :quantity_on_hand, id: :product_quantity_on_hand, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :selling_price %>
    <%= form.text_field :selling_price, id: :product_selling_price, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :cost_of_product %>
    <%= form.text_field :cost_of_product, id: :product_cost_of_product, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :shipping_weight %>
    <%= form.text_field :shipping_weight, id: :product_shipping_weight, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :image_thumbnail %>
    <%= form.text_field :image_thumbnail, id: :product_image_thumbnail, class: 'fullwidth' %>
  </div>

  <div class="field">
    <%= form.label :image_full %>
    <%= form.text_field :image_full, id: :product_image_full, class: 'fullwidth' %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<% provide(:title, "Edit #{@product.name}") %>
<% provide(:page, 'Products')  %>

<section class="edit">

  <div class="section-header">
    <h2>Editing: <%= @product.name %></h2>
  </div>

  <div class="form-wrapper">

    <%= render 'form', product: @product %>

    <%= link_to 'Back', products_path, class: 'button' %>
    <%= link_to 'Show', @product, class: 'button' %>

  </div>

</section>

app/views/products/index.html.erb
<% provide(:title, 'Products') %>
<% provide(:page, 'Products')  %>

<section class="products">

  <div class="section-header">
    <h2>Products</h2>
  </div>


  <%= link_to 'New Product', new_product_path, class: 'button' %>

  <table>
    <thead>
      <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Quantity on hand</th>
        <th>Selling price</th>
        <th>Cost of product</th>
        <th>Shipping weight</th>
        <th>Image thumbnail</th>
        <th>Image full</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.description.html_safe %></td>
          <td><%= product.quantity_on_hand %></td>
          <td><%= product.selling_price %></td>
          <td><%= product.cost_of_product %></td>
          <td><%= product.shipping_weight %></td>
          <td><%= product.image_thumbnail.truncate(20) %></td>
          <td><%= product.image_full.truncate(20) %></td>
          <td><%= link_to 'Show', product %></td>
          <td><%= link_to 'Edit', edit_product_path(product) %></td>
          <td><%= link_to 'Destroy', product, method: :delete, data: {confirm: 'Are you sure?'} %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= paginate @products %>

</section>

app/views/products/new.html.erb
<% provide(:title, 'New Product') %>
<% provide(:page, 'Products')  %>

<section class="new">

  <div class="section-header">
    <h2>Create a product</h2>
  </div>

  <div class="form-wrapper">
    <%= render 'form', product: @product %>

    <%= link_to 'Back', products_path, class: 'button' %>
  </div>

</section>

app/views/products/show.html.erb
<% provide(:title, @product.name) %>
<% provide(:page, 'Products')  %>

<section class="product">

  <div class="section-header">
    <h2><%= @product.name %></h2>
    <p>
      Rated: <%= ((image_tag 'fork.png', size: '20x20') * @product.product_reviews.average(:rating)).html_safe %>
    </p>
  </div>

  <div class="details-container">

    <p>
      <strong>Description:</strong>
      <%= @product.description.html_safe %>
    </p>

    <p>
      <strong>Quantity on hand:</strong>
      <%= @product.quantity_on_hand %>
    </p>

    <p>
      <strong>Selling price:</strong>
      <%= number_to_currency @product.selling_price %>
    </p>

    <p>
      <strong>Cost of product:</strong>
      <%= number_to_currency @product.cost_of_product %>
    </p>

    <p>
      <strong>Shipping weight:</strong>
      <%= @product.shipping_weight.to_s + ' Kg' %>
    </p>

    <p>
      <strong>Image thumbnail:</strong>
      <br>
      <%= image_tag @product.image_thumbnail %>
    </p>

    <p>
      <strong>Image full:</strong>
      <br>
      <%= image_tag @product.image_full %>
    </p>

    <p>
      <%= link_to 'Back', products_path, class: 'button' %>
      <%= link_to 'Edit', edit_product_path(@product), class: 'button' %>
    </p>

    <div>
      <strong>Reviews:</strong>
      <% @product.product_reviews.each do |review| %>
        <p>
          By: <%= review.author %><br>
          Rating: <%= ((image_tag 'fork.png', size: '20x20') * review.rating).html_safe %><br>
          <%= review.comment %><br>
          Posted <%= time_ago_in_words review.created_at %> ago<br>
          <% if current_user.try(:admin?) %>
            <%= link_to 'Remove', product_product_review_path(@product, review), method: :delete, data: {confirm: 'Are you sure?'} %>
          <% end %>
        </p>
      <% end %>
    </div>

    <div class="reviews">

      <%= form_for [@product, @product.product_reviews.build] do |form| %>

        <div class="field">
          <%= form.label :author %>
          <%= form.text_area :author, id: :author, class: 'fullwidth' %>
        </div>

        <div class="field">
          <%= form.label :comment %>
          <%= form.text_area :comment, id: :comment, class: 'fullwidth' %>
        </div>

        <div class="field">
          <%= form.label :rating, class: 'fullwidth' %>
          <%= form.select 'rating', options_for_select( (1..10) ), include_blank: true %>
        </div>

        <div class="field">
          <%= form.hidden_field :product_id %>
        </div>

        <div class="actions">
          <%= form.submit %>
        </div>

      <% end %>

    </div>

    <%= link_to 'Back', products_path, class: 'button' %>
    <%= link_to 'Edit', edit_product_path(@product), class: 'button' %>

  </div>

</section>